#ifndef QPREDIXCORE_GLOBAL_H
#define QPREDIXCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPREDIXCORE_LIBRARY)
#  define QPREDIXCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPREDIXCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPREDIXCORE_GLOBAL_H
