#ifndef QTIMESERIES_GLOBAL_H
#define QTIMESERIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTIMESERIES_LIBRARY)
#  define QTIMESERIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTIMESERIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTIMESERIES_GLOBAL_H
